Refactor 'make organism'

diff --git a/src/iedb/update-cache b/src/iedb/update-cache
--- a/src/iedb/update-cache
+++ b/src/iedb/update-cache
@@ -1,22 +1,25 @@
 #!/bin/sh
 
-# Fetch the IEDB data required by Arborist as TSV.
+# Fetch the IEDB data required by Arborist as TSV,
+# cache it in a named directory,
+# and update the `current/iedb` symlink.
 
-DATABASE=${DATABASE:-$1}
-DATABASE=${DATABASE:?'Please provide a database name'}
-CACHE="cache/iedb/${DATABASE}"
+NAME=${1:?'Please provide a cache directory name'}
+CACHE="cache/iedb/${NAME}"
+
+if [ -d "${CACHE}" ]; then
+  echo "ERROR: ${CACHE} already exists"
+  exit 1
+fi
+
+mkdir -p "${CACHE}/" || exit 1
 
 fail() {
   echo "ERROR: $1"
+  echo "Removing ${CACHE}"
+  rm -rf "${CACHE}"
   exit 1
 }
-
-if [ -d "${CACHE}" ]; then
-  fail "${CACHE} already exists"
-fi
-
-mkdir -p "${CACHE}/"
-export MYSQL_DATABASE="${DATABASE}"
 
 fetch() {
   NAME="$1"
@@ -36,7 +39,7 @@ for TABLE in epitope source object; do
   fetch "${TABLE}" "SELECT * FROM ${TABLE} ORDER BY ${TABLE}_id"
 done
 
-echo "Linking current/iedb/ to ${CACHE}"
+echo "Linking current/iedb to ${CACHE}"
 mkdir -p current
 cd current || fail 'Could not cd to current/'
 rm -f iedb
diff --git a/src/util/mysql2tsv b/src/util/mysql2tsv
--- a/src/util/mysql2tsv
+++ b/src/util/mysql2tsv
@@ -11,15 +11,39 @@
 #
 # Example: ./mysql2tsv "SELECT * FROM epitope ORDER BY epitope_id" iedb/epitope.tsv
 
-MYSQL_QUERY=${1:?'Please include a SQL query string or filename'}
-TSV_FILE=${2:?'Please provide a TSV file name'}
+usage() {
+  echo 'Usage: mysql2tsv QUERY TSV_FILE'
+  echo '  QUERY can be a MySQL/MariaDB query string or file'
+  echo ''
+  echo 'These environment variables must be set:'
+  echo '  IEDB_MYSQL_HOST'
+  echo '  IEDB_MYSQL_PORT'
+  echo '  IEDB_MYSQL_USER'
+  echo '  IEDB_MYSQL_PASSWORD'
+  echo '  IEDB_MYSQL_DATABASE'
+}
 
-MYSQL_HOST=${MYSQL_HOST:?'Please set MYSQL_HOST'}
-MYSQL_PORT=${MYSQL_PORT:-'3306'}
-MYSQL_USER=${MYSQL_USER:?'Please set MYSQL_USER'}
-MYSQL_PASSWORD=${MYSQL_PASSWORD:?'Please set MYSQL_PASSWORD'}
-MYSQL_DATABASE=${MYSQL_DATABASE:?'Please set MYSQL_DATABASE'}
+# Define fail to print usage
+fail() {
+  echo "ERROR: $1"
+  usage
+  exit 1
+}
 
+if [ -z "$1" ]; then fail 'Please provide a MySQL query or file to run'; fi
+if [ -z "$2" ]; then fail 'Please provide a TSV file to write'; fi
+
+MYSQL_QUERY="$1"
+TSV_FILE="$2"
+TEMP_FILE="$2.tmp"
+
+if [ -z "${IEDB_MYSQL_HOST}" ]; then fail 'Please set IEDB_MYSQL_HOST'; fi
+if [ -z "${IEDB_MYSQL_PORT}" ]; then fail 'Please set IEDB_MYSQL_PORT'; fi
+if [ -z "${IEDB_MYSQL_USER}" ]; then fail 'Please set IEDB_MYSQL_USER'; fi
+if [ -z "${IEDB_MYSQL_PASSWORD}" ]; then fail 'Please set IEDB_MYSQL_PASSWORD'; fi
+if [ -z "${IEDB_MYSQL_DATABASE}" ]; then fail 'Please set IEDB_MYSQL_DATABASE'; fi
+
+# Redefine fail so that it does not print usage
 fail() {
   echo "ERROR: $1"
   exit 1
@@ -34,17 +58,22 @@ command -v qsv > /dev/null || PATH="bin:$PATH"
 command -v qsv > /dev/null || fail 'Please install qsv'
 
 mysql \
-  --host="${MYSQL_HOST}" \
-  --port="${MYSQL_PORT}" \
-  --user="${MYSQL_USER}" \
-  --password="${MYSQL_PASSWORD}" \
-  "${MYSQL_DATABASE}" \
+  --host="${IEDB_MYSQL_HOST}" \
+  --port="${IEDB_MYSQL_PORT}" \
+  --user="${IEDB_MYSQL_USER}" \
+  --password="${IEDB_MYSQL_PASSWORD}" \
+  "${IEDB_MYSQL_DATABASE}" \
   --execute "${MYSQL_QUERY}" \
   --quick \
-| sed "s/\r//g" \
+> "${TEMP_FILE}"
+
+# Remove carriage returns, newlines, and NULLs.
+sed "s/\r//g" "${TEMP_FILE}" \
 | sed "s/\n/ /g" \
 | qsv replace --quiet \
   --delimiter '\t' \
   --output "${TSV_FILE}" \
   'NULL' '' \
-|| exit 0
+|| true # ignore qsv replace errors
+
+rm -f "${TSV_FILE}.tmp"
